### ISSUE TITLE
Negative KL divergence?

### ISSUE THREAD

**Issue by robinsloan** [stas-semeniuta/textvae#4]
Hello! I have a simple and possibly silly question here. In my training runs, the `kld` term, as logged to `costs` by `vae.py`, is always negative, creeping upwards toward zero. Is that expected behavior?

Then, I see that the `kld` is subtracted from `reconstruction_loss` in the calculation of the overall `cost`. Shouldn't `kld` be positive, and added to `reconstruction_loss`?

Here's an example of what I'm seeing:

![cost_graph_demo](https://cloud.githubusercontent.com/assets/40284/26360144/3a6283da-3f8c-11e7-842c-bcc45079ed65.png)

(I've set `anneal_start`=0 and `anneal_end`=100 here just for demonstration purposes.)

Thanks for a great paper and a very usable code release!

**Comment by ssemeniuta** [comment]
Hi, that's fine - strictly speaking it's negative kl divergence. The term being logged is subtracted from the final cost in lines [92 ](https://github.com/stas-semeniuta/textvae/blob/master/vae.py#L92) and [94](https://github.com/stas-semeniuta/textvae/blob/master/vae.py#L94).

I've made a couple of mistakes with signs early in the development and some of their fixes have made it into the final code. I've gotten used to seeing the minus in the kl term so I didn't even realize it was there until now. You can safely take the negative of what is logged for plotting - that's what we did in the paper.

**Comment by robinsloan** [comment]
That's super helpful -- thank you!
